/**
 * Interfaces for API error handling components
 * Implements RFC 7807 for Problem Details for HTTP APIs
 */

import { HttpStatus } from '@nestjs/common';

/**
 * Base interface for API errors following RFC 7807 standard
 */
export interface ApiError {
  /**
   * A URI reference that identifies the problem type.
   * When dereferenced, it should provide human-readable documentation for the problem type.
   */
  type?: string;

  /**
   * A short, human-readable summary of the problem type.
   * It SHOULD NOT change from occurrence to occurrence of the problem.
   */
  title: string;

  /**
   * The HTTP status code generated by the origin server for this occurrence of the problem.
   */
  status: HttpStatus;

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;

  /**
   * A URI reference that identifies the specific occurrence of the problem.
   * It may or may not yield further information if dereferenced.
   */
  instance?: string;

  /**
   * Application-specific error code
   */
  code: string;

  /**
   * ISO 8601 timestamp when the error occurred
   */
  timestamp: string;

  /**
   * Request path that caused the error
   */
  path?: string;

  /**
   * Unique request identifier for tracing
   */
  requestId?: string;

  /**
   * Optional validation errors for validation failures
   */
  validationErrors?: ValidationError[];

  /**
   * Additional properties specific to the error
   */
  [key: string]: unknown;
}

/**
 * Interface for validation errors
 */
export interface ValidationError {
  /**
   * The property path that failed validation
   */
  property: string;

  /**
   * Error message for the validation failure
   */
  message: string;

  /**
   * The value that was rejected
   */
  value?: unknown;

  /**
   * The validation constraint that failed
   */
  constraint?: string;

  /**
   * Nested validation errors (for complex objects)
   */
  children?: ValidationError[];
}

/**
 * Interface for the error response structure
 */
export interface ErrorResponse {
  /**
   * Response status (always "error" for error responses)
   */
  status: 'error';

  /**
   * Error details
   */
  error: ApiError;
}

/**
 * Interface for error context
 * Used to add contextual information to errors
 */
export interface ErrorContext {
  /**
   * Path where the error occurred
   */
  path?: string;

  /**
   * Request ID for tracing
   */
  requestId?: string;

  /**
   * User information (if applicable)
   */
  user?: {
    id: string;
    email?: string;
    [key: string]: unknown;
  };

  /**
   * Request data related to the error
   */
  requestData?: Record<string, unknown>;

  /**
   * Any additional context information
   */
  [key: string]: unknown;
}

/**
 * Interface for localized error messages
 */
export interface LocalizedErrorMessages {
  /**
   * Default message in the default locale
   */
  default: string;

  /**
   * Messages in different languages
   * Key is the language code (e.g., 'en', 'ru')
   */
  translations: Record<string, string>;
}
