FROM node:22-alpine

# Установка рабочей директории
WORKDIR /app

# Установка глобальных зависимостей
RUN npm install -g npm@latest

# Копирование файлов package.json и package-lock.json
COPY package*.json ./

# Установка зависимостей
RUN npm ci

# Копирование исходного кода
COPY . .

# Экспорт порта для Next.js
EXPOSE 3000

# Команда для запуска Next.js в режиме разработки
CMD ["npm", "run", "dev"] 