FROM node:22-alpine

# Установка рабочей директории
WORKDIR /app

# Установка глобальных зависимостей
RUN npm install -g npm@latest @nestjs/cli

# Установка дополнительных зависимостей для работы с базами данных
RUN apk add --no-cache python3 make g++ postgresql-client

# Копирование файлов package.json и package-lock.json
COPY package*.json ./

# Установка зависимостей
RUN npm ci

# Установка argon2 для хеширования паролей
RUN npm install argon2

# Копирование всего исходного кода
COPY . .

# Экспорт порта для NestJS API
EXPOSE 4000

# Команда запуска указывается в docker-compose.yml 