FROM node:22-alpine AS base

# Установка рабочей директории
WORKDIR /app

# Установка глобальных зависимостей
RUN npm install -g npm@latest

# Этап установки зависимостей
FROM base AS deps
WORKDIR /app

# Копирование файлов package.json и package-lock.json
COPY package*.json ./

# Установка зависимостей
RUN npm ci

# Этап разработки
FROM base AS dev
WORKDIR /app

# Копирование node_modules из этапа установки зависимостей
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Экспорт порта для Next.js
EXPOSE 3100

# Команда для запуска Next.js в режиме разработки с горячей перезагрузкой
CMD ["npm", "run", "dev"]

# Этап сборки
FROM base AS builder
WORKDIR /app

# Копирование node_modules из этапа установки зависимостей
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Сборка приложения Next.js
RUN npm run build

# Производственный этап
FROM base AS prod
WORKDIR /app

ENV NODE_ENV production

# Копирование только необходимых файлов из этапа сборки
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Экспорт порта для Next.js
EXPOSE 3100

# Команда для запуска Next.js в production режиме
CMD ["npm", "run", "start"] 