#!/usr/bin/env node

# Перенаправляем вывод в терминал для лучшего отображения
if sh -c ": >/dev/tty" >/dev/null 2>/dev/null; then exec >/dev/tty 2>&1; fi

# Запускаем lint-staged для проверки и форматирования файлов
npx lint-staged 